import { formatDeed, formatMortgage, VeraExam } from "./vera";

export function examToPlain(exam: VeraExam): string {
  return [
    "Title Report Review Summary",
    "",
    `Search Type: ${exam.searchType}`,
    `Client Order#: ${exam.clientOrder}`,
    `Property Address: ${exam.propertyAddress}`,
    `Search Effective Date: ${exam.searchEffectiveDate}`,
    `MIN# (if applicable): ${exam.minNumber}`,
    "",
    "Property & Tax Information",
    `Parcel ID: ${exam.parcelId}`,
    `Land Value: ${exam.landValue}`,
    `Improvements: ${exam.improvements}`,
    `Tax Status: ${exam.taxStatus}`,
    `Fiscal Year: ${exam.fiscalYear}`,
    `Mobile Home: ${exam.mobileHome}`,
    `Condo/HOA: ${exam.condoHoa}`,
    "",
    "Required Question Responses",
    `Is there an HOA or not applicable? Response: ${exam.hoaPresent}`,
    `Are there Covenants, Conditions, and Restrictions attached or Not Applicable? Response: ${exam.ccrs}`,
    `Is the HOA name and amounts listed or Not Applicable? Response: ${exam.hoaNameAmounts}`,
    `Are the Deed/Mortgage amounts and names accurate? Response: ${exam.deedMortgageAccurate}`,
    `Deed: ${formatDeed(exam.deed)}`,
    ...exam.mortgages.map((m) => formatMortgage(m)),
    `Are all document recordings available and match the report? Response: ${exam.recordingsAvailable}`,
    `Are recordings in chronological order? Response: ${exam.recordingsChronological}`,
    `Is assignment vesting accurate or Not Applicable? Response: ${exam.assignmentVesting}`,
    `Is the legal description confirmed and exact across vesting deed, DOT, and Title Report? Response: ${exam.legalDescriptionConfirmed}`,
    `Legal Description: ${exam.legalDescription}`,
    `Is the original beneficiary MERS? Response: ${exam.originalBeneficiaryMers}`,
    `Is there a Federal Tax Lien or Not Applicable? Response: ${exam.federalTaxLien}`,
    `Are there any document releases that are showing on the report? Response: ${exam.documentReleases}`,
    `Is the property secured and does the Property Address match the Deed of Trust? Response: ${exam.propertySecuredAddressMatch}`,
    `What is the Loan Document type? Response: ${exam.loanDocumentType}`,
    `What is the Recording Date? Response: ${exam.recordingDate}`,
    `What is the Loan status, including the notes? Response: ${exam.loanStatus}`,
    `Recourse? Response: ${exam.recourse}`,
    `Are there any typos or errors in the report? Response: ${exam.typosOrErrors}`,
    `Is the plat map labeled? Response: ${exam.platMapLabeled}`,
    `Is the MIN# in the run sheet? Response: ${exam.minInRunSheet}`,
    `Is the Run Sheet accurate? Response: ${exam.runSheetAccurate}`,
    "",
    "Title Report / Run Sheet Accuracy Audit",
    `Vesting Deed Information: ${exam.audit.vestingDeed}`,
    `Chain of Title: ${exam.audit.chainOfTitle}`,
    `Mortgage Information: ${exam.audit.mortgageInformation}`,
    `Tax Information: ${exam.audit.taxInformation}`,
    `Judgments and Liens: ${exam.audit.judgmentsAndLiens}`,
    `Easements and Restrictions: ${exam.audit.easementsAndRestrictions}`,
    "",
    "Pass/Fail Determination",
    `Status: ${exam.status}`,
    `Reason: ${exam.reason}`,
    "",
    "Confirmation:",
    exam.confirmation,
    "",
    "Notes / Comments",
    exam.notes,
  ].join("\n");
}
